### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by CCRami** [bitri12/Classroom_downloader#1]
Program ends with an error when trying to download a deleted file from drive 
![Screenshot 2023-12-13 100529](https://github.com/bitri12/Classroom_downloader/assets/99369909/9f9d4026-fa48-471b-a0a8-84b58638bd84)
![image](https://github.com/bitri12/Classroom_downloader/assets/99369909/85ba52f3-d8fd-4709-8f32-3aa1f76ddc9f)
![image](https://github.com/bitri12/Classroom_downloader/assets/99369909/7bd738dc-48a2-4a3a-be71-92a92c492a25)
I appreciate your work btw

**Comment by bitri12** [comment]
A fix has been uploaded on this git you can pull the new downloaded.py

**Comment by CCRami** [comment]
You're most welcome! 
Although I'm still getting the same error :/
I think the try statement in download_drive_file function should start before getting the request and file_metadata because as you can see in my terminal (first image) the error (file not found) accured when it was trying to get the metadata_file, so the download_drive_file function should be something like this:
```
def download_drive_file(classroom_service, file_id, folder_path, credentials):
    drive_service = build('drive', 'v3', credentials=credentials)
    try:
        request = drive_service.files().get_media(fileId=file_id)
        file_metadata = drive_service.files().get(fileId=file_id).execute()

        if 'mimeType' in file_metadata and 'application/vnd.google-apps' in file_metadata['mimeType']:
            request.uri = f"https://www.googleapis.com/drive/v3/files/{file_id}/export?mimeType=application/pdf"
            file_path = os.path.join(folder_path, f"{file_id}_{file_metadata['name']}.pdf")
        else:
            file_path = os.path.join(folder_path, f"{file_id}_{file_metadata['name']}")
        with open(file_path, 'wb') as file:
            downloader = MediaIoBaseDownload(file, request, chunksize=1024 * 1024)
            done = False
            while not done:
                _, done = downloader.next_chunk()
    except HttpError as e:
        if e.resp.status == 404:
            print(f"File not found: {file_id}. Skipping...")
        else:
            print(f"HTTP error: {e}")
    except Exception as e:
        print(f"Error: {e}")
```
tested it and this is my output now, it's working!
![image](https://github.com/bitri12/Classroom_downloader/assets/99369909/2d7c9aa9-d95b-4bc0-9087-ac1b892873b2)
